### ISSUE TITLE
Improve testing for typescript types and bundle.js

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#130] opened 2020-07-28 07:46 UTC
#### Reason/Context
- Parser is not only for node.js but should work in the browser too. I recently broke `bundle.js` by introducing a library that doesn't work in the browser. I don't want to break it again, but I also know that when you choose a library, it is not a common habit to check if it is isomorphic (working both on server and browser). We need a way to test if the PR is not causing `bundle.js` to fail
- We will now generate typescript types from our JSDocs which is, in my opinion, a very good thing but also a very error-prone. We need a way to test that given PR is not breaking those types

I think testing of above can be solved with one sample project, like under one umbrella.

#### Description
we need some sample project in TS that will also have a `ui` where we can run parser and test result with 
puppeteer. I was thinking that we might use `asyncapi-react` as it is already a TS project with UI but, but based on my experience, I know that it might look like best and easiest solution but it can backfire over time and writing a simple test project might be much more efficient.

**Comment by kaibra** [comment] 2020-09-21 16:01
Hey @derberg . I am fairly new in the async-api environment and just recently had a look at all the tools available.
I have one question regarding this topic ("should also work in the browser"):
Isn't this line breaking the parser in the browser: https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L45 (the call to "process.cwd()") ?

**Comment by jonaslagoni** [comment] 2020-09-21 16:39
> Isn't this line breaking the parser in the browser: https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L45 (the call to "process.cwd()") ?

Yep good catch @kaibra. Since we aren't trying to parse a file but parsing a string here
https://github.com/asyncapi/parser-js/blob/932d2dd6ee2f3e1c8ed79da7507a1a994ce86e66/test/sample_browser/index.html#L15
it is not triggered. Should be easily tested by parsing file instead of string in another test 😄

**Comment by derberg** [comment] 2020-09-22 09:53
why would you try to parse a file client-side? 🤔

**Comment by kaibra** [comment] 2020-09-22 11:35
I came to this point by looking at the react component, which has the parser as a dependency.
If I am not wrong, this line of code calls the parse function, we are talking about here:
https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/AsyncApi/AsyncApi.tsx#L200

`schema` can be a string. In my case it was a string and it failed already.

I think you have a problem with your test-setup.
You are building a bundle with `browserify`. If you look at the docs of `browserify` they say:

> Additionally, if you use any of these variables, they will be defined in the bundled output in a browser-appropriate way:
>    * process
https://www.npmjs.com/package/browserify

Looking at your bundle.js, indeed it is:
```
process.cwd=function(){return"/"}
```

**Comment by jonaslagoni** [comment] 2020-09-22 11:48
> why would you try to parse a file client-side? 🤔

Good point, don't even think it is possible without it being an url, didn't realize this yesterday 🤦

> `schema` can be a string. In my case it was a string and it failed already.

@kaibra are you saying that you are unable to parse a string with the react component?

> I think you have a problem with your test-setup.

Looked a bit further into this, and tried downloading the generated parser bundle with the browser test and opened it in Chrome where it worked fine. I tried to dig further into why the tests parses while accessing node js variables, but yea `browserify` to the rescue so I don't think the test-setup are faulty. But something might happen when interacting with React if you are having problems there.

**Comment by derberg** [comment] 2020-09-22 11:49
@kaibra exactly, browserify handles `process.cwd` properly, so the setup of bundle generation is proper, you should basically use `bundle.js` in your project, it is always a part of the release, on npm and github.

I do not remember how react component handles that without using the official bundle but as you can see, the latest version is used here https://asyncapi.github.io/asyncapi-react/ and works well.

would be great if you could report a bug separately with an error message in the details.

**Comment by kaibra** [comment] 2020-09-22 13:07
Thanks for your responses. For some reason I thought the bundle.js is just used for testing.
I had a short look again and I think I am causing the error myself....
What I tried (like maybe others before: https://github.com/asyncapi/asyncapi-react/issues/75) is to integrate the asyncapi-react component in an angular application.
When debugging a small react app, using the asyncapi-react component, I found, that the shim for process coming from node-libs-browser (-> webpack) is used. 
My angular app does not have process in place and when I render the component with a string-schema "ReactDOM.render(..." it breaks at process.cwd().

**Comment by aeworxet** [comment] 2021-02-27 10:52
**Following [https://github.com/asyncapi/asyncapi-react/issues/255](https://github.com/asyncapi/asyncapi-react/issues/255), issue is postponed until [React component](https://github.com/asyncapi/asyncapi-react) is refactored to use the majority of types from the [parser-js](https://github.com/asyncapi/parser-js).**

**Comment by magicmatatjahu** [comment] 2022-12-20 09:01
@derberg Can we close this one? In Parser v2 we have improved testing of browser version https://github.com/asyncapi/parser-js/blob/next-major/test/browser/browser.spec.ts for TS types we don't need any tests - lib is written in TS so we don't have any regression between versions, only when someone will write incorrect types, but we will see that in linter stage.

**Closed** 2022-12-20 09:04 UTC
Labels: enhancement
